name: DEPLOY

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Make a choice
        options:
        - MatchingImcClients
        - MatchingIncPriorityListings
        required: true
      commit:
        description: "Commit SHA"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          echo "choice is ${{ github.event.inputs.choice }}" / ${{ inputs.choice }}
          